before_script:
  - apt-get update -qy
  - apt-get install -y openmpi-bin libopenmpi-dev

stages:
  - test

test python3.6:
  image: python:3.6
  script:
  - pip install -r requirements.txt
  - python setup.py build_ext --inplace
  - pytest
  only:
  - master

test python3.7:
  image: python:3.7
  script:
  - pip install -r requirements.txt
  - python setup.py build_ext --inplace
  - pytest
  only:
  - master

test with_pyscf:
  image: python:3.7
  script:
  - pip install -r requirements.txt
  - pip install pyscf
  - python setup.py build_ext --inplace
  - pytest
  only:
  - master
