sudo: required

language: python

cache:
  pip: true

python:
  - "3.6"
  - "3.7"

addons:
  apt:
    packages:
      - mpich
      - libmpich-dev

before_install:
  - pip install -r requirements.txt
  - pip install pyscf
  - git clone https://github.com/pauxy-qmc/pauxy_test_data.git
  - git clone https://github.com/jsspencer/testcode.git

install:
  - python setup.py build_ext --inplace

script:
  - pytest -v
 # Temporary hack until pauxy is pip-able
  - echo $PYTHONPATH
  - export PYTHONPATH=$HOME/build/pauxy-qmc/pauxy:$PYTHONPATH
  - cd pauxy_test_data
  - mpiexec --version
# Longer parallel tests
  - python ../testcode/bin/testcode.py -v  -e ../bin/pauxy run --user-option=pauxy launch_parallel 'mpiexec -np tc.nprocs python -u'
# Test examples
  - cd ..
  - ./tools/run_examples.sh
